### ISSUE TITLE
FrozenError error on MacOS install 

### ISSUE THREAD

**Issue by sliday** [makew0rld/didder#11] opened 2022-10-17 20:52 UTC
Hi there,

After I successfully tap into `brew tap makeworld-the-better-one/tap`

I get this error:

`brew install didder
==> Downloading https://github.com/makeworld-the-better-one/didder/archive/v1.1.0.tar.gz
==> Downloading from https://codeload.github.com/makeworld-the-better-one/didder/tar.gz/refs/tags/v1.1.0
##O=#  #
==> Installing didder from makeworld-the-better-one/tap
Error: An exception occurred within a child process:
  FrozenError: can't modify frozen class`

I'm on macOS Monterey 12.6, Macbook Air M2

Please assist.

**Comment by makew0rld** [comment] 2022-11-12 01:09
Sorry, unfortunately I'm not sure how to resolve this issue, and I don't have a mac to test on at the moment.

If anyone has a mac to reproduce this issue on feel free to comment here. If anyone is familiar with Homebrew the code for the homebrew install is here: https://github.com/makeworld-the-better-one/homebrew-tap/blob/master/Formula/didder.rb

**Comment by makew0rld** [comment] 2022-12-21 04:49
Opened [this issue](https://github.com/Homebrew/homebrew-core/issues/118664) with homebrew to try and figure things out.

**Comment by gingerbeardman** [comment] 2023-02-03 23:03
I also hit this blocker.

**Comment by Kneecrust** [comment] 2023-05-19 13:12
I've taken a look using CGT and gotten the following suggestion:

> In your Homebrew code, the issue seems to be with the definition of the applications method within the install method. The applications method is defined within the install method, which is causing the error.
> 
> To resolve this issue, you should move the applications method outside of the install method.


How should I go about adjusting this and retrying the installation through homebrew?

I'd love to get this running on my Mac as I've thoroughly enjoyed it while on Windows :)

**Comment by makew0rld** [comment] 2023-05-19 23:49
>> To resolve this issue, you should move the applications method outside of the install method.

Seems easy enough, I would appreciate you testing this.

> How should I go about adjusting this and retrying the installation through homebrew?

You can try using `brew edit` to edit the formula you already tried to install. Otherwise you can download and edit [the formula file](https://github.com/makew0rld/homebrew-tap/blob/master/Formula/didder.rb), then install from that file with `brew install --build-from-source ./didder.rb`

Let me know if you can get something that works!

**Comment by Kneecrust** [comment] 2023-05-20 07:00
> > > To resolve this issue, you should move the applications method outside of the install method.
> 
> Seems easy enough, I would appreciate you testing this.

@makew0rld Yes! It's the least I can do in return for you providing this awesome tool!
> 
> > How should I go about adjusting this and retrying the installation through homebrew?
> 
> You can try using `brew edit` to edit the formula you already tried to install. Otherwise you can download and edit [the formula file](https://github.com/makew0rld/homebrew-tap/blob/master/Formula/didder.rb), then install from that file with `brew install --build-from-source ./didder.rb`
> 
> Let me know if you can get something that works!

Ah, I had done that but not found the command to install from a local formula.
Just did and the installation went through successfully!
<img width="537" alt="image" src="https://github.com/makew0rld/didder/assets/82511706/0a3336c2-4bf0-4551-ab5f-ad178b6a52c7">


Here's the adjusted formula 💪
[didder.txt](https://github.com/makew0rld/didder/files/11521753/didder.txt)

Thanks for the quick feedback!

**Comment by makew0rld** [comment] 2023-05-20 15:16
Thanks for testing! Looks like just moving the applications method as you mentioned. I've updated my tap. Can you uninstall didder, and try and install it from my tap now? You might have to rerun the `brew tap` command, I'm not sure.

If everything goes well I will close this issue.

**Comment by Kneecrust** [comment] 2023-05-21 06:16
Hi @makew0rld!
Uninstalled Didder, resynced your tap, and installed Didder once again using the brew install didder command and it went through successfully!

Glad to have this awesome app up and running and available to Mac users again! ❤️

**Closed as completed** 2023-05-21 15:52 UTC
Labels: bug, question
