### ISSUE TITLE
Stuck on 'required flags "palette, out, in" not set.'

### ISSUE THREAD

**Issue by Kneecrust** [makew0rld/didder#8] opened 2022-02-27 20:09 UTC
Hi! 

I'm sorry if this is not the right way to reach out. 
Couldn't find any info on this in the docs sadly.

I'm not able to get didder to do anything with any image. 
It keeps giving me back the line from the title. 
'required flags "palette, out, in" not set.'

Any tips on how to get past this? 
Added the didder.exe to my PATH as specified, so it shouldn't be that. 

Thanks!

**Comment by makew0rld** [comment] 2022-02-27 20:31
Hello! It sounds like you are not setting the required flags for didder to work. Please see the [manual](https://github.com/makeworld-the-better-one/didder/blob/main/MANPAGE.md).

When running didder, you must specify the `--palette`, `--in`, and `--out` flags, or their short versions. For example: 

```
didder -i david.png -o david_dithered.png --palette 'black white' bayer 4x4
```

**Comment by Kneecrust** [comment] 2022-03-01 07:51
Hi!
Strangely on the docs I found that palette came before -i and -o.
Now switching them around at least there’s some progress. Thanks!
Now it’s stating that the colors I input are not recognised.  
Any notion of why it does not recognise them? Thanks in advance!

**Comment by Kneecrust** [comment] 2022-03-01 07:57
Seem to have solved the color issue by switching to Hex and using "double quotes" over 'single quotes'.

**Comment by makew0rld** [comment] 2022-03-01 13:51
> Strangely on the docs I found that palette came before -i and -o.
> Now switching them around at least there’s some progress. 

Strange, the order shouldn't matter.

> Now it’s stating that the colors I input are not recognised.  
> Any notion of why it does not recognise them?

If you want help in the future you have to paste the command you ran here, otherwise I can't tell you what the issue is. Anyway glad it works now.

**Comment by makew0rld** [comment] 2022-03-01 13:51
I'll close this for now, let me know if you still have any issues.

**Closed as completed by makew0rld** 2022-03-01 13:51 UTC
Labels: question

**Comment by SHiLLySiT** [comment] 2022-05-24 20:01
@makeworld-the-better-one I'm also seeing the same error with the example command from the README when running on Windows 10:
`didder --palette 'black white' -i input.jpg -o test.png bayer 16x16`

As per @Kneecrust 's suggestion, changing the single quotes to double quotes fixed the issue:
`didder --palette "black white" -i input.jpg -o test.png bayer 16x16`

**Comment by makew0rld** [comment] 2022-05-24 20:42
@SHiLLySiT thanks for reporting as well. Must be some Windows terminal issue. I switched to using double quotes in d583a29.
